### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by mightyiam** [gytis-ivaskevicius/nix2vim#1]
I didn't try yet, but I'd like to look into it some time. I will follow "watch" the releases. Do you intend to make GitHub releases? Or is there any other way to follow them?

**Comment by gytis-ivaskevicius** [comment]
Not sure how am going to go about releases, it would be nice thing to have but i find it a little botthersome

**Comment by mightyiam** [comment]
Well, don't do it just for me.
