### ISSUE TITLE
Manage _just_ dependencies with nix

### ISSUE THREAD

**Issue by the-argus** [gytis-ivaskevicius/nix2vim#7]
I would like to use nix to manage my packer plugins and their configurations, because those are the elements of my config that don't involve functions or any idiosyncratic lua/vim stuff that wouldn't be possible (as far as I'm aware) with this flake. How can I go about _partially_ using nix2vim, with raw lua alongside it?

**Comment by DieracDelta** [comment]
Would the `lua` attribute fit your goal? It just appends raw lua to the generated lua. [Example](https://github.com/DieracDelta/vimconfig/blob/master/modules/treesitter.nix#L196)

**Comment by gytis-ivaskevicius** [comment]
you can also do stuff like `lua = builtins.readFile ./something.lua`. Is this issue resolved?

**Comment by the-argus** [comment]
yep. I'm migrating my config now.
