### ISSUE TITLE
Support require('xxx.yyy').zzz as use."xxx.yyy".zzz

### ISSUE THREAD

**Issue by ghost** [gytis-ivaskevicius/nix2vim#9]
Hello, Gytis, first, thanks for create this plugins. Now I'm moving my neovim configurations from lua to nix, in telescope and alpha.nvim configuration, my configuration have some statement like:
``` lua
-- alpha.nvim
require('alpha').setup(require('alpha.themes.startify').config)
-- telescope.nvim
require('telescope').load_extension('fzy_native')
```
I reference the docs and code for `lib/api.options.nix` writing the following code:
``` nix
{
  ...
  # alpha.nvim
  alpha.setup = use.'alpha.themes.startify'.config;
  # telescope.nvim, syntax like calling a function
  use.'telescope'.load_extensions 'fzy_native';
  ...
}
```
For the current code design, that's illegal, if want make it work, must use the `lua = ''''` to wrap those statement. idk have a better throughts for using nix to configuring neovim, maybe need add some new features or functions for lua to nix api?
P.S.: Just throughts :)

**Comment by gytis-ivaskevicius** [comment]
I believe something like `setup.alpha = rawLua "require('alpha.themes.startify').config";` would work.

Maybe you got in mind how the feature should be implemented? or maybe you could share minimal Lua config and ill give it some thought

**Comment by ghost** [comment]
For example, like loading telescope extensions:
``` lua
-- Loading fzy_native telescope extensions
require('telescope').load_extensions('fzy_native')
-- or 
require('telescope').load_extensions "fzy_native"
```
In my throught, in nix, the code will possible like:
``` nix
use."telescope".load_extensions "fzy_native"
```
Because in nix call a function is: `function_name function_args`, like: `builtins.isString "testing"`
So, I'm thinking it will be work, but actually nix give me error for this.
Sorry for my poor english. :)

**Comment by gytis-ivaskevicius** [comment]
So nix is pure, so it must be assigned to something in some way.
This would look like this:
`use.telescope.load_extensions = dsl.callWith  "fzy_native"`

There may be some issues with ordering (load_extension before setup), maybe some separate property should be added

**Comment by ghost** [comment]
> So nix is pure, so it must be assigned to something in some way. This would look like this: `use.telescope.load_extensions = dsl.callWith "fzy_native"`
> 
> There may be some issues with ordering (load_extension before setup), maybe some separate property should be added

Yep, that is I'm was thinking.
